#!/usr/bin/env python3
"""Pack original, native-resolution ClearUI Instrument glyphs; no scaling."""
from pathlib import Path
import argparse
import re

ROOT = Path(__file__).resolve().parents[1]
HEIGHT = 14

def glyphs():
    result = {}
    for line in (ROOT / 'assets/fonts/radio-sans.txt').read_text().splitlines():
        if not line or line.startswith('#'):
            continue
        code, *rows = [int(value, 16) for value in line.split()]
        assert code not in result and len(rows) <= HEIGHT
        assert all(0 <= row < 128 for row in rows)
        result[code] = rows + [0] * (HEIGHT - len(rows))
    assert set(result) == set(range(32, 127))
    return result

def compact_glyphs():
    # The same original optical small face already used by the menu system.
    source = (ROOT / 'App/ui/clearui_text.c').read_text()
    result = {32: [0] * 7}
    for char, rows in re.findall(r"\['((?:\\.|[^'])*)'-32\] = \{([^}]+)\}", source):
        code = ord(bytes(char, 'ascii').decode('unicode_escape'))
        result[code] = [int(v) for v in rows.split(',')]
    assert set(result) == set(range(32, 127))
    # Real descenders in the radio's eighth pixel, unlike seven-row menus.
    for char, rows in {
        '0': [14,17,17,21,17,17,14],
        'I': [14,4,4,4,4,4,14],
        'g': [0,0,15,17,17,15,1,14],
        'j': [2,0,2,2,2,2,2,12],
        'p': [0,0,30,17,17,30,16,16],
        'q': [0,0,15,17,17,15,1,1],
        'y': [0,0,17,17,17,15,1,14],
    }.items():
        result[ord(char)] = rows
    return result

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    large, compact = glyphs(), compact_glyphs()
    widths, offsets, data, small = [], [], [], []
    for code in range(32, 127):
        rows = large[code]
        occupied = [x for x in range(7) if any(row & (64 >> x) for row in rows)]
        # Tabular digits avoid width jitter while tuning; names proportional.
        columns = range(7) if 48 <= code <= 57 else range(min(occupied), max(occupied)+1) if occupied else range(2)
        packed = [sum(bool(row & (64 >> x)) << y for y, row in enumerate(rows)) for x in columns]
        packed += [0, 0]
        # Add the requested one-pixel rightward stroke, within existing advance.
        packed = [column | (packed[i-1] if i else 0) for i, column in enumerate(packed)]
        widths.append(len(packed))
        offsets.append(len(data))
        for column in packed:
            data.extend((column & 255, column >> 8))
        optical = [sum(bool(row & (16 >> x)) << y for y, row in enumerate(compact[code])) for x in range(5)] + [0]
        small.extend(column | (optical[i-1] if i else 0) for i, column in enumerate(optical))

    def array(kind, name, values):
        chunks = [', '.join(str(v) for v in values[i:i+16]) for i in range(0,len(values),16)]
        return f'const {kind} {name}[{len(values)}] = {{\n    ' + ',\n    '.join(chunks) + '\n};\n'
    output = '''/* SPDX-License-Identifier: Apache-2.0
 * Original ClearUI Instrument pixel artwork, 2026.
 * Generated by tools/build_clearui_font.py. Native pixels, no resampling.
 */
#include "clearui_font.h"

'''
    output += array('uint16_t','gClearUIFontOffsets',offsets)
    output += array('uint8_t','gClearUIFontWidths',widths)
    output += array('uint8_t','gClearUIFontData',data)
    output += array('uint8_t','gClearUIFontSmall',small)
    path = ROOT / 'App/clearui_font.c'
    if args.check:
        assert path.read_text() == output, 'Regenerate radio font tables'
        print('Native radio font source and generated tables match (95 glyphs, both sizes).')
    else:
        path.write_text(output)
        print(f'Generated native instrument face: {len(data)} large + {len(small)} compact bytes')

if __name__ == '__main__':
    main()
